name: 修改后端配置
description: 修改后端配置
operationId: updateBackendConfig

variables:
#    url
    host_maga: ${ENV(ENV_OPENAPI_INNER_DATA_HOST)}
    apiVer_maga: ${ENV(ENV_API_VERSION)}
    regionId_maga: ${ENV(ENV_APIM_REGIONID)}
#    header
    header_maga:
        Content-Type: application/json;charset=UTF-8
        x-jdcloud-pin: ${ENV(ENV_PIN)}
#    json
    groupName_maga: groupName_maga
    description_maga: description_maga
    prefix_maga: prefix_maga
    keyCheck_maga: keyCheck_maga
    authType_maga: authType_maga
    prefixStrip_maga: prefixStrip_maga
    groupType_maga: groupType_maga
    jdsfName_maga: jdsfName_maga
    jdsfRegistryName_maga: jdsfRegistryName_maga
    jdsfId_maga: jdsfId_maga
#    hooks
    serviceLine_maga: ${ENV(ENV_SERVICELINE_APIM)}
    openapiYaml_maga: nofile
    openApiAk_maga: ${ENV(ENV_OPENAPI_SYS_AK)}
    openApiSk_maga: ${ENV(ENV_OPENAPI_SYS_SK)}
    apiVersion_maga: v1
    
request:
    url: $host_maga/$api_ver_maga/regions/$regionId_maga/apiGroups/$apiGroupId_maga
    method: PUT
    headers: $header_maga
    json:
        groupName: $groupName_maga
        description: $description_maga
        prefix: $prefix_maga
        keyCheck: $keyCheck_maga
        authType: $authType_maga
        prefixStrip: $prefixStrip_maga
        groupType: $groupType_maga
        jdsfName: $jdsfName_maga
        jdsfRegistryName: $jdsfRegistryName_maga
        jdsfId: $jdsfId_maga
setup_hooks:
    - ${hook_update_jdcloud_request($request, $openApiAk_maga, $openApiSk_maga, $serviceLine_maga, $apiVersion_maga, $openapiYaml_maga, $regionId_maga)}
teardown_hooks:
    - ${hook_print("teardown_hooks for config")
