testcases:
    正常删除配置版本，返回200:
        testcase: testcases\jdsf\apis\deleteAppConfig-200.yaml
        parameters:
            userpin:
                - ${ENV(ENV_USER_PIN)}
            usererps:
                - ${ENV(ENV_USER_ERP)}
            appconfigid:
                - 95