name: 根据云翼服务树中应用名称查询服务网格的入口分流规则配置-$product-$env-$host
variables:
    host: ${ENV(ENV_JDMESH_WEB_BASE_URL)}
    expected_status_code: 200
    product: productpage
    env: pre
    ingress: []
    requestid: ${get_timestamp(13)}${gen_random_string(19)}
    headers:
        ajax-id: $requestid
        x-jdcloud-request-id: $requestid
    global_headers: {"ajax-id": "$requestid", "x-jdcloud-request-id": "$requestid"}
    cookies:
         _ga: ${ENV(ENV_COOKIES)}

# Fiddler request:
#POST http://jdmesh-ui.mesh.cn-north-1.jdcloud.com/openApi/jdmesh/updateIngress HTTP/1.1
#Host: jdmesh-ui.mesh.cn-north-1.jdcloud.com
#Connection: keep-alive
#Content-Length: 240
#Accept: application/json
#Origin: http://jdmesh-ui.mesh.cn-north-1.jdcloud.com
#User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
#Content-Type: application/json;charset=UTF-8
#Referer: http://jdmesh-ui.mesh.cn-north-1.jdcloud.com/?tab=ingressConfig
#Accept-Encoding: gzip, deflate
#Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,pl;q=0.7
#Cookie: _ga=GA1.2.1393266954.1552618748; 3AB9D23F7A4B3C9B=N56LRR2BO5SZE5CC45ZOBB2KSDATYNJX4LX3CNGKBXC32FFGVFAUZOX2JS5CFMDTB3WES7TJYJD22HNLXDUL4LZQ3I; jdcloud_sitelang=cn; __jda=36325045.1554091325970812602438.1554091326.1562125380.1563271869.47; csrfToken=cg-vLyPWfm-wUHQMO2E2UjWJ
#
#{"params":{
#    "appId":"productpage",
#    "env":"pre",
#    "ingressSpec":{
#        "appId":"productpage",
#        "ingresses":[
#           {"weightPolicy":null,"headerPolicy":null,"uriPolicy":null,"defaultRoute":"*","useWaf":false,"host":"reviews.ingress.mesh.cn-east-2-stag.jdcloud.com"}
#            ]
#    }}}
#
#{"params":{
#    "appId":"productpage",
#    "env":"pre",
#    "ingressSpec":{
#        "appId":"productpage",
#        "ingresses":[
#            {"weightPolicy":null,"headerPolicy":null,"uriPolicy":null,"defaultRoute":"gray","useWaf":false,"host":"productpage-g.ingress.mesh.cn-east-2-stag.jdcloud.com"},
#            {"weightPolicy":null,"headerPolicy":null,"uriPolicy":null,"defaultRoute":"az1","useWaf":false,"host":"productpage.ingress.mesh.az1.jdcloud.com"},
#            {"weightPolicy":null,"headerPolicy":null,"uriPolicy":null,"defaultRoute":"az2","useWaf":false,"host":"productpage.ingress.mesh.az2.jdcloud.com"},
#            {"weightPolicy":null,"headerPolicy":null,"uriPolicy":null,"defaultRoute":"*","useWaf":false,"host":"productpage.ingress.mesh.azx.jdcloud.com"},
#            {"weightPolicy":null,"headerPolicy":[{"header":{"x-jdcloud-test-jdsm-route":"healthcheckfailed"},"subsetId":"healthcheckfailed"}],"uriPolicy":null,"defaultRoute":"product","useWaf":false,"host":"productpage.ingress.mesh.cn-east-2-stag.jdcloud.com"}
#            ]
#    }}}
#
#
#{"params":{"appName":"jdmesh-productpage-test","env":"pre","ingressSpec":{"appName":"jdmesh-productpage-test","ingresses":[{"weightPolicy":null,"headerPolicy":[{"header":{"x-jdcloud-test-jdsm-route-healthcheck":"healthcheckfailed"},"subsetId":"healthcheckfailed"}],"uriPolicy":null,"defaultRoute":"gray","useWaf":false,"host":"jdmesh-productpage-test-g.ingress.mesh.cn-east-2-stag.jdcloud.com"},{"weightPolicy":null,"headerPolicy":null,"uriPolicy":null,"defaultRoute":"product","useWaf":false,"host":"jdmesh-productpage-test.abc.com"},{"weightPolicy":null,"headerPolicy":null,"uriPolicy":null,"defaultRoute":"*","useWaf":false,"host":"jdmesh-productpage-test.ingress.mesh.cn-east-2-stag.jdcloud.com"},{"weightPolicy":null,"headerPolicy":null,"uriPolicy":null,"defaultRoute":"*","useWaf":false,"host":"jdmesh-productpage-test.abcd.com"}]}}}
#

request:
    url: $host/openApi/jdmesh/updateIngress
    method: POST
    headers: $headers
    cookies: $cookies

    json:
        params:
            appName: $product
            env: $env
            ingressSpec:
                appName: $product
                ingresses: $ingress

setup_hooks:
    - ${hook_update_request_insert_global_headers($request, $global_headers)}

validate:
    - eq: ["status_code", $expected_status_code]

response:
    - {
        "requestId":"bkp38mrcm0dgj9ic3abh3t0kf5v0psbc","error":null,
        "result":{"ingresses":null},
        "responseObj":{"size":0,"timeout":0,"nonce":"e817e2a9-2044-408b-bfb7-76fe2daf753a"}
      }