name: 调用reviews接口- $headers - $expected_status_code
variables:
    host: ${ENV(ENV_PRODUCT_PAGE_BASE_URL)}
    productid: 0
    requestid: ${get_timestamp(13)}${gen_random_string(19)}
    headers:
        ajax-id: $requestid
        x-jdcloud-request-id: $requestid
    global_headers: {"ajax-id": "$requestid", "x-jdcloud-request-id": "$requestid"}
request:
    url: $host/api/v1/products/$productid/reviews
    headers: $headers
    method: GET
    # JSON

setup_hooks:
    - ${hook_update_request_insert_global_headers($request, $global_headers)}
